import type { WorkflowOptions } from "./workflows.js";

/**
 * `.gitlab-ci.yml` written by `sdlc init --code-host gitlab` (3.7): the same
 * jobs the GitHub Actions workflows carry — the eval suite as the
 * config-change gate, validation on every merge request, detection on a
 * schedule, the production gate's required status on the default branch —
 * in one pipeline file. Create-only, like every file init writes.
 */
export const GITLAB_CI_FILE = ".gitlab-ci.yml";

function installLines(opts: WorkflowOptions, bin: string): string {
  const install = opts.install === undefined ? "pnpm" : opts.install;
  if (install === null) return `    # No lockfile when sdlc init ran: add an install step here if \`${bin}\` needs one.\n`;
  if (install === "pnpm") return "    - corepack enable\n    - pnpm install --frozen-lockfile\n";
  if (install === "yarn") return "    - corepack enable\n    - yarn install --immutable\n";
  return "    - npm ci\n";
}

export function gitlabCi(opts: WorkflowOptions & { cron?: string } = {}): string {
  const bin = opts.bin ?? "npx sdlc";
  return `# Generated by sdlc init --code-host gitlab — the console's CI jobs for GitLab (blueprint §15, build-order 3.7).
#
# sdlc-validate         lifecycle files validate on every merge request.
# sdlc-evals            the eval suite as the config-change gate (FR-52): an MR touching CLAUDE.md, .claude/** or
#                       sdlc/config.yaml runs the suite and \`sdlc evals gate\` fails the job below threshold; scheduled
#                       and web-triggered runs keep their run file on the sdlc/evals-runs branch. Make this job a
#                       required check ("pipelines must succeed") on the protected default branch.
# sdlc-detect           the deterministic detection script on a schedule (FR-60); commits nothing.
# sdlc-production-gate  on every push to the default branch, publishes the \`sdlc/rollback-rehearsed\` status on the
#                       pushed commit from the committed deploy.yaml records (FR-40). Deploys and authorizes nothing.
#
# Variables to set on the project (Settings → CI/CD → Variables, masked):
#   SDLC_GITLAB_TOKEN   an access token with \`api\` and \`write_repository\` scope: the evals job pushes its run file with it
#                       and the production gate publishes the status with it (a CI job token cannot do either).
# The adapter addresses the project through CI_API_V4_URL and CI_PROJECT_ID, which GitLab CI sets by itself; the
# token travels in a header and a git credential helper — never in a URL.
stages:
  - sdlc

default:
  image: node:22
  before_script:
${installLines(opts, bin)}
sdlc-validate:
  stage: sdlc
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - ${bin} validate

sdlc-evals:
  stage: sdlc
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - CLAUDE.md
        - ".claude/**/*"
        - sdlc/config.yaml
        - "evals/cases/**/*"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
  variables:
    GIT_DEPTH: 0
    SDLC_IDENTITY: sdlc-bot@sdlc.local
  script:
    - |
      case "$CI_PIPELINE_SOURCE" in
        merge_request_event) TRIGGER=config-pr ;;
        schedule) TRIGGER=schedule ;;
        *) TRIGGER=manual ;;
      esac
    - git checkout -B "\${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:-$CI_COMMIT_REF_NAME}" "$CI_COMMIT_SHA"
    - ${bin} evals run --trigger "$TRIGGER" --json
    - |
      # keep the run file: on the MR's source branch, else on sdlc/evals-runs (the token comes from a credential helper, not the URL)
      git -c credential.helper='!f() { echo "username=oauth2"; echo "password=$SDLC_GITLAB_TOKEN"; }; f' \\
        push "https://$CI_SERVER_HOST/$CI_PROJECT_PATH.git" "HEAD:refs/heads/\${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:-sdlc/evals-runs}"
    - if [ "$CI_PIPELINE_SOURCE" = "merge_request_event" ]; then ${bin} evals gate; fi

sdlc-detect:
  stage: sdlc
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
  script:
    - ${bin} detect
  artifacts:
    when: always
    paths:
      - .sdlc-state/snapshots

sdlc-production-gate:
  stage: sdlc
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "web"
  variables:
    GIT_DEPTH: 0
    GITLAB_TOKEN: $SDLC_GITLAB_TOKEN
  script:
    - ${bin} production-gate $SDLC_CHANGE --sha "$CI_COMMIT_SHA" --publish
`;
}
