/**
 * GitHub Actions workflows written by `sdlc init` (blueprint §15 "CI:
 * workflows generated by sdlc init"; build-order 2.5). Create-only, like
 * every other file init writes: teams edit them afterwards.
 */
/** Package manager the Install step uses; `null` writes no step (no lockfile when init ran). */
export type InstallStep = "pnpm" | "npm" | "yarn" | null;

export interface WorkflowOptions {
  /** `evals.schedule` cron from config, when set. */
  schedule?: string;
  /** Command that runs the CLI in CI (default `npx sdlc`; `init --sdlc-bin` points it at a team's own install). */
  bin?: string;
  /** Install step for the checkout (default pnpm, the lockfile decides at init). */
  install?: InstallStep;
}

function installStep(install: InstallStep, bin: string): string {
  if (install === null) return `      # No lockfile when sdlc init ran: add an install step here if \`${bin}\` needs one.\n`;
  const run = install === "pnpm" ? "|\n          corepack enable\n          pnpm install --frozen-lockfile" : install === "yarn" ? "|\n          corepack enable\n          yarn install --immutable" : "npm ci";
  return `      - name: Install\n        run: ${run}\n`;
}

export function evalsWorkflow(opts: WorkflowOptions = {}): string {
  const bin = opts.bin ?? "npx sdlc";
  const install = installStep(opts.install === undefined ? "pnpm" : opts.install, bin);
  const schedule = opts.schedule ? `  schedule:\n    - cron: "${opts.schedule}"\n` : "";
  return `# Generated by sdlc init — the eval suite as the config-change gate (blueprint FR-52).
# A PR touching CLAUDE.md, .claude/** or sdlc/config.yaml runs the suite; \`sdlc evals gate\` fails the
# check when the run is below threshold (incomplete never passes) and lists regressed cases with
# before/after output. Scheduled and manual runs push their run file to the sdlc/evals-runs branch.
# Make "sdlc evals / config-change gate" a required status in branch protection to block merges.
name: sdlc evals
on:
  pull_request:
    paths:
      - CLAUDE.md
      - ".claude/**"
      - sdlc/config.yaml
      - "evals/cases/**"
  workflow_dispatch:
${schedule}permissions:
  contents: write
  pull-requests: write
concurrency:
  group: sdlc-evals-\${{ github.head_ref || github.ref_name }}
  cancel-in-progress: false
jobs:
  suite:
    name: config-change gate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: \${{ github.head_ref || github.ref_name }}
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
${install}      - name: Run the suite
        run: ${bin} evals run --trigger \${{ github.event_name == 'pull_request' && 'config-pr' || github.event_name == 'schedule' && 'schedule' || 'manual' }} --json
        env:
          SDLC_IDENTITY: sdlc-bot@sdlc.local
      - name: Keep the run file (PR branch)
        if: github.event_name == 'pull_request'
        run: git push origin HEAD:\${{ github.head_ref }}
      - name: Keep the run file (sdlc/evals-runs)
        if: github.event_name != 'pull_request'
        env:
          GH_TOKEN: \${{ github.token }}
        run: |
          git push origin HEAD:refs/heads/sdlc/evals-runs
          gh pr create --head sdlc/evals-runs --base "\${{ github.event.repository.default_branch }}" --title "sdlc: eval suite runs" --body "Run files the suite committed on schedule or by hand. Merge to bring the history onto the default branch." 2>/dev/null || true
      - name: Config-change gate
        if: github.event_name == 'pull_request'
        run: ${bin} evals gate
`;
}

export function validateWorkflow(opts: WorkflowOptions = {}): string {
  const bin = opts.bin ?? "npx sdlc";
  const install = installStep(opts.install === undefined ? "pnpm" : opts.install, bin);
  return `# Generated by sdlc init — lifecycle files validate on every pull request.
name: sdlc validate
on:
  pull_request:
permissions:
  contents: read
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
${install}      - run: ${bin} validate
`;
}

/** Detection from CI (3.4): the script on a schedule, its table and evidence in the job log, the job red at 2σ or beyond. */
export function detectWorkflow(opts: WorkflowOptions & { cron?: string } = {}): string {
  const bin = opts.bin ?? "npx sdlc";
  const install = installStep(opts.install === undefined ? "pnpm" : opts.install, bin);
  return `# Generated by sdlc init — the deterministic detection script on a schedule (blueprint FR-60, build-order 3.4).
# Runs every \`source:\` in bands.yaml, prints the Bands table with the sources' output verbatim, and fails the job
# at 2σ or beyond (exit 2) or when a source fails (exit 1). It commits nothing: the console's own schedule
# (\`sdlc serve --engine\`, bands.yaml detectEvery) is what raises triage items and diagnose/propose jobs.
name: sdlc detect
on:
  schedule:
    - cron: "${opts.cron ?? "*/30 * * * *"}"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  detect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
${install}      - name: Detect
        run: ${bin} detect
      - name: Keep the snapshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sdlc-snapshots
          path: .sdlc-state/snapshots
          if-no-files-found: ignore
`;
}

/**
 * The production gate's required check from CI (3.6): on every push to the
 * default branch, `sdlc/rollback-rehearsed` is published on the pushed commit
 * from the committed deploy.yaml records. A team's own deploy workflow gates
 * on this job; the workflow itself deploys nothing and cannot open the gate.
 */
export function productionGateWorkflow(opts: WorkflowOptions = {}): string {
  const bin = opts.bin ?? "npx sdlc";
  const install = installStep(opts.install === undefined ? "pnpm" : opts.install, bin);
  return `# Generated by sdlc init — the production gate's required check (blueprint FR-40 production-gate, build-order 3.6).
# On a push to the default branch, \`sdlc production-gate --sha <commit> --publish\` reads the committed deploy.yaml of the
# change merged at that commit and publishes \`sdlc/rollback-rehearsed\`: green only when a rollback was rehearsed with
# success in a non-production environment at the merged commit (or the merged PR's tested head). The job is red otherwise
# and green when no change records the commit. Make a production deploy workflow \`needs:\` this job. Nothing here deploys
# or authorizes: production is deployed by a person holding the gate's role with \`sdlc deploy <env> <CHG>\` (or the console).
name: sdlc production gate
on:
  push:
  workflow_dispatch:
    inputs:
      change:
        description: "Change id (CHG-NNNN); defaults to the change merged at the checked-out commit"
        required: false
permissions:
  contents: read
  statuses: write
  checks: write
jobs:
  rollback-rehearsed:
    if: github.event_name == 'workflow_dispatch' || github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
${install}      - name: Production gate check
        run: ${bin} production-gate \${{ inputs.change }} --sha \${{ github.sha }} --publish
        env:
          GITHUB_TOKEN: \${{ github.token }}
          GITHUB_REPOSITORY: \${{ github.repository }}
`;
}

export const WORKFLOW_FILES = { evals: ".github/workflows/sdlc-evals.yml", validate: ".github/workflows/sdlc-validate.yml", detect: ".github/workflows/sdlc-detect.yml", productionGate: ".github/workflows/sdlc-production-gate.yml" } as const;
