/**
 * GitHub Actions workflows written by `sdlc init` (blueprint §15 "CI:
 * workflows generated by sdlc init"; build-order 2.5). Create-only, like
 * every other file init writes: teams edit them afterwards.
 */
export interface WorkflowOptions {
  /** `evals.schedule` cron from config, when set. */
  schedule?: string;
  /** Command that runs the CLI in CI (default `npx sdlc`). */
  bin?: string;
}

export function evalsWorkflow(opts: WorkflowOptions = {}): string {
  const bin = opts.bin ?? "npx sdlc";
  const schedule = opts.schedule ? `  schedule:\n    - cron: "${opts.schedule}"\n` : "";
  return `# Generated by sdlc init — the eval suite as the config-change gate (blueprint FR-52).
# A PR touching CLAUDE.md, .claude/** or sdlc/config.yaml runs the suite; \`sdlc evals gate\` fails the
# check when the run is below threshold (incomplete never passes) and lists regressed cases with
# before/after output. Scheduled and manual runs push their run file to the sdlc/evals-runs branch.
# Make "sdlc evals / config-change gate" a required status in branch protection to block merges.
name: sdlc evals
on:
  pull_request:
    paths:
      - CLAUDE.md
      - ".claude/**"
      - sdlc/config.yaml
      - "evals/cases/**"
  workflow_dispatch:
${schedule}permissions:
  contents: write
  pull-requests: write
concurrency:
  group: sdlc-evals-\${{ github.head_ref || github.ref_name }}
  cancel-in-progress: false
jobs:
  suite:
    name: config-change gate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: \${{ github.head_ref || github.ref_name }}
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install
        run: |
          corepack enable
          pnpm install --frozen-lockfile
      - name: Run the suite
        run: ${bin} evals run --trigger \${{ github.event_name == 'pull_request' && 'config-pr' || github.event_name == 'schedule' && 'schedule' || 'manual' }} --json
        env:
          SDLC_IDENTITY: sdlc-bot@sdlc.local
      - name: Keep the run file (PR branch)
        if: github.event_name == 'pull_request'
        run: git push origin HEAD:\${{ github.head_ref }}
      - name: Keep the run file (sdlc/evals-runs)
        if: github.event_name != 'pull_request'
        env:
          GH_TOKEN: \${{ github.token }}
        run: |
          git push origin HEAD:refs/heads/sdlc/evals-runs
          gh pr create --head sdlc/evals-runs --base "\${{ github.event.repository.default_branch }}" --title "sdlc: eval suite runs" --body "Run files the suite committed on schedule or by hand. Merge to bring the history onto the default branch." 2>/dev/null || true
      - name: Config-change gate
        if: github.event_name == 'pull_request'
        run: ${bin} evals gate
`;
}

export function validateWorkflow(opts: WorkflowOptions = {}): string {
  const bin = opts.bin ?? "npx sdlc";
  return `# Generated by sdlc init — lifecycle files validate on every pull request.
name: sdlc validate
on:
  pull_request:
permissions:
  contents: read
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install
        run: |
          corepack enable
          pnpm install --frozen-lockfile
      - run: ${bin} validate
`;
}

export const WORKFLOW_FILES = { evals: ".github/workflows/sdlc-evals.yml", validate: ".github/workflows/sdlc-validate.yml" } as const;
