import type { EntityOf, SchemaName } from "../src/index.js";

export const SHA = "0123456789abcdef0123456789abcdef01234567";
export const SHA2 = "fedcba9876543210fedcba9876543210fedcba98";
export const TS = "2026-09-03T10:00:00Z";
export const ULID = "01J8Z6Q7Y2K3M4N5P6Q7R8S9TA";

const human = { type: "human", id: "dkapper01@gmail.com", role: "po" } as const;

const configRef = {
  claudeMdSha: SHA,
  skills: [{ name: "brand", version: "1.2.0" }],
  hooksSha: SHA2,
  model: "claude-opus-5",
};

/** One valid value per schema; the oracle for the golden tests. */
export const samples: { [K in SchemaName]: EntityOf<K> } = {
  change: {
    schema: 1,
    id: "CHG-0042",
    title: "Invoice CSV export",
    kind: "feature",
    risk: "routine",
    created: { by: "dkapper01@gmail.com", at: TS },
    origin: { type: "idea" },
    record: null,
    cycle: 1,
    repro: null,
    closed: null,
  },
  event: {
    schema: 1,
    id: ULID,
    ts: TS,
    seq: 3,
    cycle: 1,
    actor: human,
    event: "gate.accepted",
    data: { gate: 1, artifactSha: SHA, source: "cli" },
    sha: SHA2,
  },
  config: {
    schema: 1,
    defaultRole: "po",
    identities: [{ id: "dkapper01@gmail.com", name: "Daniel", roles: ["po", "eng"] }],
    thresholds: { autoFilesMax: 12, maxLoopRounds: 5 },
    records: { intent: "repo", spec: "repo" },
    evals: { mode: "continuous", threshold: 0.9 },
    eligibility: { coverage: "lenient" },
  },
  tasks: {
    schema: 1,
    changeId: "CHG-0042",
    cycle: 1,
    tasks: [
      {
        id: "export-endpoint",
        title: "Add /export endpoint",
        files: ["src/export.ts", "test/export.test.ts"],
        sequential: false,
        target: "GET /export returns CSV; test passes",
        state: "proposed",
      },
    ],
  },
  "eval-case": {
    schema: 1,
    id: "CASE-0001",
    prompt: "Export invoices as CSV",
    checks: [{ name: "test", cmd: "pnpm test -- export" }],
    source: { type: "change", ref: "CHG-0042" },
    owner: "platform",
    added: TS,
    status: "active",
    paths: ["src/export.ts"],
  },
  "eval-run": {
    schema: 1,
    id: "RUN-0001",
    trigger: "manual",
    configRef,
    results: [{ caseId: "CASE-0001", pass: true, output: "1 passed" }],
    passRate: 1,
    threshold: 0.9,
    verdict: "pass",
    startedAt: TS,
    finishedAt: TS,
  },
  "per-change-run": {
    schema: 1,
    n: 1,
    changeId: "CHG-0042",
    cycle: 1,
    worktree: "CHG-0042/export-endpoint",
    headSha: SHA,
    fileSet: ["src/export.ts"],
    configRef,
    results: [{ caseId: "CASE-0001", pass: true, output: "1 passed" }],
    commandResults: [{ name: "build", cmd: "pnpm build", exitCode: 0, pass: true, output: "" }],
    verdict: "green",
    startedAt: TS,
  },
  round: {
    schema: 1,
    n: 3,
    ts: TS,
    results: [
      { name: "build", pass: true, exitCode: 0, outputExcerpt: "" },
      { name: "test", pass: true, exitCode: 0, outputExcerpt: "5 passed" },
    ],
  },
  "repro-proof": {
    schema: 1,
    testPath: "test/export.test.ts",
    failureReason: "expected 200, received 500",
    sha: SHA,
    output: "AssertionError: expected 200",
    confirmedBy: "dkapper01@gmail.com",
    confirmedAt: TS,
  },
  pr: {
    schema: 1,
    provider: "local",
    branch: "CHG-0042/export-endpoint",
    baseBranch: "main",
    headSha: SHA,
    openedAt: TS,
    reviewers: [],
    checks: [{ name: "evidence", verdict: "pass" }],
    planMatches: true,
  },
  deploy: { schema: 1, env: "staging", version: "1.4.0", at: TS, status: "succeeded" },
  triage: {
    schema: 1,
    id: "TRI-0042",
    tier: "3σ",
    src: "metric:p95-latency",
    title: "p95 latency breached 3σ",
    evidence: "p95 = 840ms vs baseline 310ms",
    createdAt: TS,
    status: "open",
  },
  finding: {
    schema: 1,
    id: "SEC-0118",
    scannerId: "scan-7f3a",
    sev: "high",
    conf: 0.92,
    validated: true,
    repo: "invoicing",
    title: "SQL injection in invoice filter",
    desc: "User input reaches the query builder unescaped.",
    status: "new",
  },
  proposal: {
    schema: 1,
    id: "PRP-0007",
    type: "claude-md-line",
    text: "Run pnpm lint before reporting done.",
    citations: ["CHG-0004", "CHG-0007"],
    status: "open",
    createdAt: TS,
  },
  "intent-frontmatter": {
    schema: 1,
    id: "CHG-0042",
    artifact: "intent",
    cycle: 1,
    author: "dkapper01@gmail.com",
    created: TS,
    status: "draft",
  },
  "spec-frontmatter": {
    schema: 1,
    id: "CHG-0042",
    artifact: "spec",
    cycle: 1,
    intent_sha: SHA,
    prompt_ref: null,
    skills: [{ name: "brand", version: "1.2.0" }],
    concerns: [{ id: "C1", policy: "privacy", owner: "legal", resolved: false }],
    created: TS,
  },
  "plan-frontmatter": {
    schema: 1,
    id: "CHG-0042",
    artifact: "plan",
    cycle: 1,
    spec_sha: SHA,
    rev: 2,
    accepted_by: null,
    accepted_at: null,
    acceptance_line: "GET /export returns CSV for 3 fixture invoices",
  },
  bands: {
    baselineWindow: "30d",
    metrics: [
      {
        metric: "p95_latency_ms",
        baseline: 310,
        rules: ["western-electric"],
        tiers: {
          "1sigma": { action: "log" },
          "2sigma": { action: "diagnose", tools: ["Read", "Grep", "Bash(gh run view *)"] },
          "3sigma": { action: "propose", routes: ["pr", "runbook:rollback"] },
        },
      },
    ],
    runbooks: ["rollback"],
  },
  "incident-frontmatter": {
    schema: 1,
    id: "CHG-0012",
    artifact: "incident",
    cycle: 1,
    src: "metric:error-rate",
    tier: "incident",
    created: TS,
  },
};
