import type { EntityOf, SchemaName } from "../src/index.js";

export const SHA = "0123456789abcdef0123456789abcdef01234567";
export const SHA2 = "fedcba9876543210fedcba9876543210fedcba98";
export const TS = "2026-09-03T10:00:00Z";
export const ULID = "01J8Z6Q7Y2K3M4N5P6Q7R8S9TA";

const human = { type: "human", id: "dkapper01@gmail.com", role: "po" } as const;

const configRef = {
  claudeMdSha: SHA,
  skills: [{ name: "brand", version: "1.2.0" }],
  hooksSha: SHA2,
  model: "claude-opus-5",
};

/** One valid value per schema; the oracle for the golden tests. */
export const samples: { [K in SchemaName]: EntityOf<K> } = {
  change: {
    schema: 1,
    id: "CHG-0042",
    title: "Invoice CSV export",
    kind: "feature",
    risk: "routine",
    created: { by: "dkapper01@gmail.com", at: TS },
    origin: { type: "idea" },
    record: null,
    cycle: 1,
    repro: null,
    closed: null,
  },
  event: {
    schema: 1,
    id: ULID,
    ts: TS,
    seq: 3,
    cycle: 1,
    actor: human,
    event: "gate.accepted",
    data: { gate: 1, artifactSha: SHA, source: "cli" },
    sha: SHA2,
  },
  config: {
    schema: 1,
    defaultRole: "po",
    identities: [{ id: "dkapper01@gmail.com", name: "Daniel", roles: ["po", "eng"] }],
    thresholds: { autoFilesMax: 12, maxLoopRounds: 5 },
    records: { intent: "repo", spec: "repo" },
    evals: { mode: "continuous", threshold: 0.9 },
    eligibility: { coverage: "lenient" },
  },
  tasks: {
    schema: 1,
    changeId: "CHG-0042",
    cycle: 1,
    tasks: [
      {
        id: "export-endpoint",
        title: "Add /export endpoint",
        files: ["src/export.ts", "test/export.test.ts"],
        sequential: false,
        target: "GET /export returns CSV; test passes",
        state: "proposed",
      },
    ],
  },
  "eval-case": {
    schema: 1,
    id: "CASE-0001",
    prompt: "Export invoices as CSV",
    checks: [{ name: "test", cmd: "pnpm test -- export" }],
    source: { type: "change", ref: "CHG-0042" },
    owner: "platform",
    added: TS,
    status: "active",
    paths: ["src/export.ts"],
  },
  "eval-run": {
    schema: 1,
    id: "RUN-0001",
    trigger: "manual",
    configRef,
    results: [{ caseId: "CASE-0001", pass: true, output: "1 passed" }],
    passRate: 1,
    threshold: 0.9,
    verdict: "pass",
    startedAt: TS,
    finishedAt: TS,
  },
  "per-change-run": {
    schema: 1,
    n: 1,
    changeId: "CHG-0042",
    cycle: 1,
    worktree: "CHG-0042/export-endpoint",
    headSha: SHA,
    fileSet: ["src/export.ts"],
    configRef,
    results: [{ caseId: "CASE-0001", pass: true, output: "1 passed" }],
    commandResults: [{ name: "build", cmd: "pnpm build", exitCode: 0, pass: true, output: "" }],
    verdict: "green",
    startedAt: TS,
  },
  round: {
    schema: 1,
    n: 3,
    ts: TS,
    results: [
      { name: "build", pass: true, exitCode: 0, outputExcerpt: "" },
      { name: "test", pass: true, exitCode: 0, outputExcerpt: "5 passed" },
    ],
  },
  "repro-proof": {
    schema: 1,
    testPath: "test/export.test.ts",
    failureReason: "expected 200, received 500",
    sha: SHA,
    output: "AssertionError: expected 200",
    confirmedBy: "dkapper01@gmail.com",
    confirmedAt: TS,
  },
  pr: {
    schema: 1,
    provider: "local",
    branch: "CHG-0042/export-endpoint",
    baseBranch: "main",
    headSha: SHA,
    openedAt: TS,
    reviewers: [],
    checks: [{ name: "evidence", verdict: "pass" }],
    planMatches: true,
  },
  deploy: { schema: 1, env: "staging", version: "1.4.0", at: TS, status: "succeeded" },
  triage: {
    schema: 1,
    id: "TRI-0042",
    tier: "3σ",
    src: "metric:p95-latency",
    title: "p95 latency breached 3σ",
    evidence: "p95 = 840ms vs baseline 310ms",
    createdAt: TS,
    status: "open",
  },
  finding: {
    schema: 1,
    id: "SEC-0118",
    scannerId: "scan-7f3a",
    sev: "high",
    conf: 0.92,
    validated: true,
    repo: "invoicing",
    title: "SQL injection in invoice filter",
    desc: "User input reaches the query builder unescaped.",
    status: "new",
  },
  proposal: {
    schema: 1,
    id: "PRP-0007",
    type: "claude-md-line",
    text: "Run pnpm lint before reporting done.",
    citations: ["CHG-0004", "CHG-0007"],
    status: "open",
    createdAt: TS,
  },
  "intent-frontmatter": {
    schema: 1,
    id: "CHG-0042",
    artifact: "intent",
    cycle: 1,
    author: "dkapper01@gmail.com",
    created: TS,
    status: "draft",
  },
  "spec-frontmatter": {
    schema: 1,
    id: "CHG-0042",
    artifact: "spec",
    cycle: 1,
    intent_sha: SHA,
    prompt_ref: null,
    skills: [{ name: "brand", version: "1.2.0" }],
    concerns: [{ id: "C1", policy: "privacy", owner: "legal", resolved: false }],
    created: TS,
  },
  "plan-frontmatter": {
    schema: 1,
    id: "CHG-0042",
    artifact: "plan",
    cycle: 1,
    spec_sha: SHA,
    rev: 2,
    accepted_by: null,
    accepted_at: null,
    acceptance_line: "GET /export returns CSV for 3 fixture invoices",
  },
  bands: {
    baselineWindow: "30d",
    metrics: [
      {
        metric: "p95_latency_ms",
        baseline: 310,
        rules: ["western-electric"],
        tiers: {
          "1sigma": { action: "log" },
          "2sigma": { action: "diagnose", tools: ["Read", "Grep", "Bash(gh run view *)"] },
          "3sigma": { action: "propose", routes: ["pr", "runbook:rollback"] },
        },
      },
    ],
    runbooks: ["rollback"],
  },
  "metric-snapshot": {
    schema: 1,
    metric: "p95_latency_ms",
    ts: TS,
    baseline: 310,
    current: 842,
    sigma: 40,
    tier: 3,
    breached: true,
    source: { command: "scripts/p95.sh", exitCode: 0, output: "842\n" },
  },
  "runbook-run": {
    schema: 1,
    id: "RBK-0001",
    runbook: "rollback",
    command: "kubectl rollout undo deploy/export",
    metric: "p95_latency_ms",
    triage: "TRI-0044",
    session: "sess-band1",
    actor: { type: "agent", id: "claude-code@sdlc.local" },
    startedAt: TS,
    finishedAt: TS,
    exitCode: 0,
    output: "deployment.apps/export rolled back\n",
  },
  "incident-frontmatter": {
    schema: 1,
    id: "CHG-0012",
    artifact: "incident",
    cycle: 1,
    src: "metric:error-rate",
    tier: "incident",
    created: TS,
  },
  "change-export": {
    schema: 1,
    kind: "change-export",
    exportedAt: TS,
    exportedBy: { id: "auditor@example.com", name: "Ada Auditor" },
    ref: SHA,
    change: {
      schema: 1,
      id: "CHG-0042",
      title: "Invoice CSV export",
      kind: "feature",
      risk: "routine",
      created: { by: "dkapper01@gmail.com", at: TS },
      origin: { type: "idea" },
      record: null,
      cycle: 1,
      repro: null,
      closed: null,
    },
    derived: { stage: 2, stageName: "Design", status: "Agent producing spec.md", acceptedGates: [1], valid: true, validationErrors: [] },
    cycles: [
      {
        cycle: 1,
        archived: false,
        dir: "sdlc/changes/CHG-0042",
        artifacts: [{ index: 0, name: "intent.md", path: "sdlc/changes/CHG-0042/intent.md", sha: SHA, frontMatter: { id: "CHG-0042", artifact: "intent" }, content: "---\nid: CHG-0042\n---\n# Intent\n" }],
        decisions: [{ eventId: ULID, cycle: 1, seq: 3, ts: TS, gate: 1, decision: "accepted", by: { id: "dkapper01@gmail.com", role: "po" }, source: "cli", artifactSha: SHA, note: null, commit: SHA2 }],
        pr: null,
        artifactPrs: [],
        merges: [],
        runs: [],
        findings: [],
        deploy: null,
      },
    ],
    events: [{ schema: 1, id: ULID, ts: TS, seq: 3, cycle: 1, actor: human, event: "gate.accepted", data: { gate: 1, artifactSha: SHA, source: "cli" } }],
    evalCases: [],
    contentHash: { algorithm: "sha256", over: "canonical-json", value: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" },
  },
  "claude-security-delivery": {
    schema: 1,
    source: "claude-security",
    deliveryId: "cs-delivery-0001",
    run: { id: "scan-2026-09-08-01", url: "https://security.example/runs/scan-2026-09-08-01", startedAt: TS, finishedAt: TS },
    repo: { name: "invoicing", commit: SHA },
    findings: [
      { id: "7f3a91", status: "open", title: "SQL injection in invoice filter", severity: "high", confidence: 0.97, validated: true, description: "User-supplied `sort` reaches the query builder unescaped.", evidence: "src/invoice/list.ts:41", location: { path: "src/invoice/list.ts", startLine: 41, endLine: 43 }, rule: "sql-injection/raw-query", cwe: "CWE-89", url: "https://security.example/findings/7f3a91" },
      { id: "a41c07", status: "resolved", title: "Webhook secret compared with ==", severity: "medium", confidence: 0.88 },
    ],
  },
  "claude-tag-delivery": {
    schema: 1,
    source: "claude-tag",
    deliveryId: "ct-delivery-0001",
    channel: { workspace: "slack", name: "#support", id: "C0SUPPORT1" },
    message: { id: "1757318400.000100", permalink: "https://veri.slack.com/archives/C0SUPPORT1/p1757318400000100", author: "Mara Lindqvist", text: "Customers see last month's invoice PDF.", postedAt: TS },
    thread: [{ id: "1757318460.000200", author: "Eli Ng", text: "The PDF cache key is the customer id only.", postedAt: TS }],
    tags: ["billing"],
    title: "Wrong invoice PDF from email links",
  },
};
